# Generated by Django 6.1.1 on 2026-09-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(upload_to='productImages/')),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('shirt', 'Shirt'), ('pant', 'Pant'), ('borka', 'Borka'), ('kids', 'Kids'), ('shoes', 'Shoes')], max_length=30)),
            ],
        ),
    ]
